### ISSUE TITLE
ReviewAppを削除する際、そのApp経由で作られたAWSのリソースも削除したい

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/reviewapp-operator#69]
Dreamkast上からAWS IVSやMediaLiveのリソースを作成できるのだが、ReviewAppを削除する際に消し忘れると残りっぱなしになってしまう。PRをマージしたりクローズしてReviewAppが削除される際、AWS側のリソースも自動的に消えてくれるとうれしい。ReviewAppのマニフェストを消しているのはreviewapp-operatorなので、これに消す機能を追加するとよさそうなのでは？ということでまずはIssueを立てた。

AWSのリソースにReviewAppの情報を含める必要があるが、それは https://github.com/cloudnativedaysjp/dreamkast/issues/1034 で実施済み。

**Comment by takaishi** [comment]
reviewapp_controllerのreconcileDelete内でAWSのAPIを実行してリソースを削除する、というのはすぐ実装できそう。だけどそれでいいのか？感はある。

**Comment by ShotaKitazawa** [comment]
自分的には方針は以下のどちらかかなと思ってます。

* reviewapp-operator で監視している PR が閉じたときに任意のスクリプトの実行を hook する機構を実装する
* reviewapp-operator はあくまで「ArgoCD でデプロイするマニフェストを増減させる」だけとして、 例えば AWS リソースを増減させたい場合は [AWS Service Operator for Kubernetes](https://aws.amazon.com/jp/blogs/opensource/aws-service-operator-kubernetes-available/) を利用するようにする
    * reviewapp-operator 自体への追加実装はなし

Dreamkast 的に今から下の案をするのはまあまあ大変だと思うので、必要であれば案1の実装を issue に積もうと思いますがどうでしょう？

**Comment by ShotaKitazawa** [comment]
というか以下の要件から案2はそもそも取れないのか、案1が良さそうな気がします:pray:

> Dreamkast上からAWS IVSやMediaLiveのリソースを作成できる

**Comment by ShotaKitazawa** [comment]
案1を取るならば次に考えるべきこととして、そのスクリプトをどこで実行するかですね。以下の3案があると思ってます。

1. reviewapp-operator controller 内で実行
する
    * 要考慮: 実行するスクリプト自体はどこに持つか？ (Reviewappリソースのannotations? ConfigMap?)
2. reviewapp-operator に Job 実行用のコンポーネントを作り、reviewapp-operator から RPC でフック
    * 要考慮: 案1と同じ
3. reviewapp-operator から k8s Job リソースを作成する
    * 多分、JobTemplate 的な CR を新たに作成することになる

スケールしやすい、実行結果が見やすいあたりの点から案3が良いように感じてます。

**Comment by takaishi** [comment]
案1の3がいい感じに疎結合にできそうですね〜！！issue積んでもらってもよいですか？

**Comment by takaishi** [comment]
削除するツールはリポジトリ切ってコンテナ化しておけば開発も楽そう。

**Comment by takaishi** [comment]
削除はRakeタスクで実行できるように実装済み｡

```
bundle exec rake aws:delete_review_app_resources
```

**Comment by ShotaKitazawa** [comment]
MEMO : #78 , #80 で preStopJob の機構を実装したが、以下の既知の問題がある。

* JobTemplate から生成される Job を操作する際に metadata.name を使ってオブジェクトの取得やログ出力をしているため、 metadata.generatedName を利用できない
    * 任意の label を付与 & その label を使ったオブジェクトの取得をするように直す

* https://github.com/cloudnativedaysjp/reviewapp-operator/blob/14552d442c6bec7629655bca0829e2d005c779fa/controllers/reviewapp_controller_phase.go#L300-L330
